### ISSUE TITLE
I did everything but still get this message please help

### ISSUE THREAD

**Issue by 1none2** [RealBabyPotato/Autofisher#1]
I get this message "appears to be a directory, but should be a file. Please specify the *full path* to the autohotkey.exe executable file"
btw I did change the file location.

**Comment by jadenbn** [comment]
Hi! I haven't worked on this project in a bit but if you're still getting that error, try installing AutoHotKey [here](https://www.autohotkey.com/), or alternatively, point the path directly to the AutoHotKey executable provided in the repo.
